name = "alicesaidhi/vide"
version = "0.4.1-test.4"
description = "Unofficial fork of vide for the new type solver. Comes with instance types!"
authors = ["centau"]
repository = "https://github.com/centau/vide"
includes = ["LICENSE.md", "README.md", "src/**", "pesde.toml"]
license = "MIT"

[target]
environment = "roblox"
build_files = ["src"]
lib = "/src/init.luau"

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"